### ISSUE TITLE
Data set for test phase?

### ISSUE THREAD

**Issue by nhatuan84** [PJansson/speech#1]
Hi,

Could you upload the data set for test phase:
I have not found the file below:
/home/data/audio/data/test/audio/clip_704535a4f.wav

Thanks.
Br,

**Comment by pjnssn** [comment]
> Hi,
> 
> Could you upload the data set for test phase:
> I have not found the file below:
> /home/data/audio/data/test/audio/clip_704535a4f.wav
> 
> Thanks.
> Br,

Hi,

Sorry for the late reply. The entire dataset can be found [here](https://www.kaggle.com/c/tensorflow-speech-recognition-challenge). There is also a newer version of the dataset released Speech Commands V2 I believe, that fixed many of the issues with the dataset on Kaggle.
